# Generated by Django 4.1.10 on 2023-07-14 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('mobile', models.CharField(max_length=20, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('observer', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observação')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('neighborhood', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('conjugate', models.CharField(blank=True, max_length=200, null=True, verbose_name='Conjugue')),
                ('marital_status', models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Separado', 'Separado'), ('Divorciado', 'Divorciado'), ('Viuvo', 'Viúvo')], max_length=20, verbose_name='Estado Civil')),
                ('is_retired', models.BooleanField(default=False, verbose_name='Aposentado')),
                ('education', models.CharField(blank=True, choices=[('Ensino Médio', 'Ensino Médio'), ('Graduação', 'Graduação'), ('Pós-graduação', 'Pós-graduação'), ('Mestrado ou Doutorado', 'Mestrado ou Doutorado'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Pós-graduação', 'Pós-graduação'), ('Especialização', 'Especialização'), ('Técnico', 'Técnico'), ('Tecnológico', 'Tecnológico')], max_length=22, null=True, verbose_name='Formação')),
                ('promise_date', models.DateField(blank=True, null=True, verbose_name='Data da Promessa')),
                ('marriage_date', models.DateField(blank=True, null=True, verbose_name='Data do Matrimonio')),
                ('mentor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mentor')),
                ('parish', models.CharField(blank=True, max_length=255, null=True, verbose_name='De qual paroquia pertence')),
                ('updateAt', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('createAt', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Profissão')),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profissão',
                'verbose_name_plural': 'Profissões',
                'db_table': 'Profession',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('member', models.ManyToManyField(related_name='trainers', to='members.members', verbose_name='Membro Associado')),
            ],
            options={
                'verbose_name': 'Formador',
                'verbose_name_plural': 'Formadores',
            },
        ),
        migrations.AddField(
            model_name='members',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.profession', verbose_name='Profissão'),
        ),
        migrations.AddField(
            model_name='members',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
