# Generated by Django 4.1.10 on 2023-07-14 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='profile_image',
            field=models.ImageField(default=2, upload_to='profile_images/% d/% m/% Y/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='members',
            name='mentor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mentor(a)'),
        ),
        migrations.AlterField(
            model_name='members',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='trainers', to='members.members', verbose_name='Membro Associado'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
