# Generated by Django 4.1.10 on 2023-07-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_profile_image_alter_members_mentor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='updateAt',
        ),
        migrations.AlterField(
            model_name='members',
            name='profile_image',
            field=models.ImageField(upload_to='profile_images/%d-%m-%Y'),
        ),
    ]
