# Generated by Django 4.1.10 on 2023-07-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_members_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
