# Generated by Django 4.1.10 on 2023-07-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_members_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='date_of_birth',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
