# Generated by Django 4.1.10 on 2023-07-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_members_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
