# Generated by Django 4.1.10 on 2023-07-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_members_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='parish',
        ),
        migrations.AddField(
            model_name='members',
            name='church',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='De qual igreja pertence'),
        ),
    ]
