# Generated by Django 4.2.3 on 2023-07-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_remove_members_parish_members_church'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='date_of_birth',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
