# Generated by Django 4.1.10 on 2023-07-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_remove_members_parish_members_church'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='pastorais',
            field=models.CharField(blank=True, choices=[('cozinha', 'Cozinha'), ('central de comunicacao', 'Central de comunicação'), ('lanchonete', 'Lanchonete(Quarta/Quinta'), ('merce', 'Merce'), ('liturgia', 'Liturgia'), ('adoracao', 'Adoração'), ('limpeza', 'Limpeza'), ('loja', 'Loja'), ('bazar', 'Bazar'), ('sao cristovao', 'São Cristóvão'), ('apoio', 'Apoio'), ('intercessao', 'Intecessão'), ('sao miguel', 'São Miguel'), ('musicos', 'Músicos'), ('camarim', 'Camarim')], max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='date_of_birth',
            field=models.DateField(default='2023-07-26', verbose_name='Data de Nascimento'),
            preserve_default=False,
        ),
    ]
