# Generated by Django 4.2.3 on 2023-07-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_members_date_of_birth'),
        ('members', '0012_members_pastorais_alter_members_date_of_birth'),
    ]

    operations = [
    ]
