# Generated by Django 4.2.3 on 2023-07-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_merge_20230726_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='mentor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Orientador(a)'),
        ),
    ]
