# Generated by Django 4.2.3 on 2023-07-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_alter_members_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='elo',
            field=models.CharField(blank=True, choices=[('1_elo', '1º elo'), ('2_elo', '2º elo'), ('3_elo', '3º elo'), ('vocacionado', 'Vocacionado'), ('amigo_da_comunidade', 'Amigo da Comunidade')], max_length=50, null=True),
        ),
    ]
