# Generated by Django 4.1.10 on 2023-08-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_members_elo_alter_members_mentor'),
        ('members', '0015_members_elo'),
    ]

    operations = [
    ]
