# Generated by Django 4.1.10 on 2023-08-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_merge_20230801_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='pastorais',
            field=models.CharField(blank=True, choices=[('cozinha', 'Cozinha'), ('central de comunicacao', 'Central de comunicação'), ('lanchonete', 'Lanchonete(Quarta/Quinta)'), ('merce', 'Merce'), ('liturgia', 'Liturgia'), ('adoracao', 'Adoração'), ('limpeza', 'Limpeza'), ('loja', 'Loja'), ('bazar', 'Bazar'), ('sao cristovao', 'São Cristóvão'), ('apoio', 'Apoio'), ('intercessao', 'Intecessão'), ('sao miguel', 'São Miguel'), ('musicos', 'Músicos'), ('camarim', 'Camarim')], max_length=23, null=True),
        ),
    ]
