# Generated by Django 4.1.10 on 2023-08-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_members_mentor'),
        ('members', '0017_alter_members_pastorais'),
    ]

    operations = [
    ]
