# Generated by Django 4.1.10 on 2023-08-08 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_merge_20230807_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='pastorais',
        ),
    ]
