# Generated by Django 4.1.10 on 2023-08-08 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastorais', '0002_alter_pastorais_options_remove_pastorais_member'),
        ('members', '0019_remove_members_pastorais'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='pastoral',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pastorais.pastorais'),
            preserve_default=False,
        ),
    ]
