# Generated by Django 4.1.10 on 2023-08-08 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastorais', '0002_alter_pastorais_options_remove_pastorais_member'),
        ('members', '0020_members_pastoral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='pastoral',
        ),
        migrations.AddField(
            model_name='members',
            name='pastorais',
            field=models.ManyToManyField(to='pastorais.pastorais'),
        ),
        migrations.CreateModel(
            name='MembroPastoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.members')),
                ('pastoral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastorais.pastorais')),
            ],
            options={
                'unique_together': {('pastoral', 'member')},
            },
        ),
    ]
