# Generated by Django 4.1.10 on 2023-08-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_remove_members_pastoral_members_pastorais_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembroPastoral',
        ),
    ]
