# Generated by Django 4.1.10 on 2023-08-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_delete_membropastoral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='elo',
            field=models.CharField(choices=[('1_elo', '1º elo'), ('2_elo', '2º elo'), ('3_elo', '3º elo'), ('vocacionado', 'Vocacionado'), ('amigo_da_comunidade', 'Amigo da Comunidade')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
