# Generated by Django 4.2.4 on 2023-08-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_alter_members_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='updateAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado Em'),
        ),
    ]
