# Generated by Django 4.2.4 on 2023-08-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_rename_date_of_birth_members_dtnascimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='mobile',
            new_name='celular',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='phone',
            new_name='telefone',
        ),
    ]
