# Generated by Django 4.2.4 on 2023-08-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_rename_mobile_members_celular_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='updateAt',
            new_name='atualizadoEm',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='createAt',
            new_name='criadoEm',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='observer',
            new_name='observacao',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='gender',
            new_name='sexo',
        ),
    ]
