# Generated by Django 4.2.4 on 2023-08-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_rename_updateat_members_atualizadoem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='marriage_date',
            new_name='data_matrimonio',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='promise_date',
            new_name='data_promessa',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='dtNascimento',
            new_name='dt_Nascimento',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='full_name',
            new_name='nome_completo',
        ),
    ]
