# Generated by Django 4.2.4 on 2023-08-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_rename_marriage_date_members_data_matrimonio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='data_matrimonio',
            new_name='dt_matrimonio',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='data_promessa',
            new_name='dt_promessa',
        ),
    ]
