# Generated by Django 4.2.4 on 2023-08-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastorais', '0003_rename_pastoral_pastorais_nome'),
        ('members', '0030_rename_dt_nascimento_members_dt_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='pastorais',
            field=models.ManyToManyField(blank=True, related_name='pastorais', to='pastorais.pastorais', verbose_name='Pastorais'),
        ),
    ]
