# Generated by Django 4.2.4 on 2023-08-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_rename_church_members_igreja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='is_retired',
            new_name='aposentado',
        ),
        migrations.AddField(
            model_name='members',
            name='afastado',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Afastado'),
        ),
        migrations.AddField(
            model_name='members',
            name='atestado_obito',
            field=models.FileField(blank=True, null=True, upload_to='atestado_obito/%d-%m-%Y'),
        ),
        migrations.AddField(
            model_name='members',
            name='falecido',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Falecido'),
        ),
    ]
