# Generated by Django 4.2.4 on 2023-08-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0033_rename_is_retired_members_aposentado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='aposentado',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Aposentado'),
        ),
    ]
