# Generated by Django 4.2.4 on 2023-08-14 22:22

import apps.elos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0035_alter_members_atestado_obito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='elo',
            field=models.CharField(max_length=50, verbose_name=apps.elos.models.Elos),
        ),
    ]
