# Generated by Django 4.2.4 on 2023-08-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastorais', '0003_rename_pastoral_pastorais_nome'),
        ('elos', '0002_alter_elos_options'),
        ('members', '0037_remove_members_elo_members_elos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='elos',
            field=models.ManyToManyField(blank=True, related_name='elos', to='elos.elos', verbose_name='Elos'),
        ),
        migrations.AlterField(
            model_name='members',
            name='pastorais',
            field=models.ManyToManyField(blank=True, related_name='pastorais', to='pastorais.pastorais', verbose_name='Pastorais'),
        ),
    ]
