# Generated by Django 4.2.4 on 2023-08-14 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0038_alter_members_elos_alter_members_pastorais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='elos',
            new_name='elo',
        ),
    ]
