# Generated by Django 4.2.4 on 2023-08-14 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0039_rename_elos_members_elo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='elo',
            new_name='elos',
        ),
    ]
