# Generated by Django 4.2.4 on 2023-08-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0040_rename_elo_members_elos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='elos',
        ),
        migrations.AddField(
            model_name='members',
            name='elo',
            field=models.CharField(choices=[('1_elo', '1º elo'), ('2_elo', '2º elo'), ('3_elo', '3º elo')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
