# Generated by Django 4.2.4 on 2023-08-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0041_remove_members_elos_members_elo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='profile_image',
            new_name='imagem_perfil',
        ),
    ]
