# Generated by Django 4.2.4 on 2023-08-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0042_rename_profile_image_members_imagem_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('membro', models.ManyToManyField(blank=True, related_name='formadores', to='members.members', verbose_name='Membro Associado')),
            ],
            options={
                'verbose_name': 'Formador',
                'verbose_name_plural': 'Formadores',
            },
        ),
        migrations.DeleteModel(
            name='Trainers',
        ),
    ]
