# Generated by Django 4.2.4 on 2023-08-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0043_formadores_delete_trainers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='zip_code',
            new_name='cep',
        ),
        migrations.AlterField(
            model_name='members',
            name='education',
            field=models.CharField(blank=True, choices=[('ensino fundamental', 'Ensino Fundamental'), ('Ensino Médio', 'Ensino Médio'), ('Graduação', 'Graduação'), ('Pós-graduação', 'Pós-graduação'), ('Mestrado ou Doutorado', 'Mestrado ou Doutorado'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Pós-graduação', 'Pós-graduação'), ('Especialização', 'Especialização'), ('Técnico', 'Técnico'), ('Tecnológico', 'Tecnológico')], max_length=22, null=True, verbose_name='Formação'),
        ),
    ]
