# Generated by Django 4.2.4 on 2023-08-19 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0044_rename_zip_code_members_cep_alter_members_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='conjugate',
            new_name='conjugue',
        ),
    ]
