# Generated by Django 4.2.4 on 2023-08-19 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0045_rename_conjugate_members_conjugue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='igreja',
        ),
    ]
