# Generated by Django 4.2.4 on 2023-08-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0046_remove_members_igreja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='marital_status',
            new_name='estado_civil',
        ),
    ]
