# Generated by Django 4.2.4 on 2023-08-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0047_rename_marital_status_members_estado_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='education',
            field=models.CharField(blank=True, choices=[('aprendizado_online', 'Aprendizado Online'), ('bacharelado', 'Bacharelado'), ('doutorado', 'Doutorado'), ('educacao_continuada', 'Educação Continuada'), ('ensino fundamental', 'Ensino Fundamental'), ('ensino medio', 'Ensino Médio'), ('especializacao', 'Especialização'), ('graduacao', 'Graduação'), ('licenciatura', 'Licenciatura'), ('mestrado', 'Mestrado'), ('mba', 'MBA (Master of Business Administration)'), ('phd', 'Ph.D.'), ('pos-graduacao', 'Pós-graduação'), ('tecnico', 'Técnico'), ('tecnologo', 'Tecnologo')], max_length=22, null=True, verbose_name='Formação'),
        ),
        migrations.AlterField(
            model_name='members',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
