# Generated by Django 4.2.4 on 2023-08-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastorais', '0004_alter_pastorais_nome'),
        ('members', '0049_rename_members_membros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membros',
            name='pastorais',
            field=models.ManyToManyField(blank=True, related_name='membros', to='pastorais.pastorais', verbose_name='Pastorais'),
        ),
    ]
