# Generated by Django 4.1.10 on 2023-08-01 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0013_alter_members_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocacionados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('observacao', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observação')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('conjugue', models.CharField(blank=True, max_length=200, null=True, verbose_name='Conjugue')),
                ('estado_civil', models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Separado', 'Separado'), ('Divorciado', 'Divorciado'), ('Viuvo', 'Viúvo')], max_length=20, verbose_name='Estado Civil')),
                ('aposentado', models.BooleanField(default=False, verbose_name='Aposentado')),
                ('formacao_academica', models.CharField(blank=True, choices=[('Ensino Médio', 'Ensino Médio'), ('Graduação', 'Graduação'), ('Pós-graduação', 'Pós-graduação'), ('Mestrado ou Doutorado', 'Mestrado ou Doutorado'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Pós-graduação', 'Pós-graduação'), ('Especialização', 'Especialização'), ('Técnico', 'Técnico'), ('Tecnológico', 'Tecnológico')], max_length=22, null=True, verbose_name='Formação Acadêmica')),
                ('data_matrimonio', models.DateField(blank=True, null=True, verbose_name='Data do Matrimonio')),
                ('orientador', models.CharField(blank=True, max_length=255, null=True, verbose_name='Orientador(a)')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_vocacionados/%d-%m-%Y')),
                ('pastorais', models.CharField(blank=True, choices=[('cozinha', 'Cozinha'), ('central de comunicacao', 'Central de comunicação'), ('lanchonete', 'Lanchonete(Quarta/Quinta)'), ('merce', 'Merce'), ('liturgia', 'Liturgia'), ('adoracao', 'Adoração'), ('limpeza', 'Limpeza'), ('loja', 'Loja'), ('bazar', 'Bazar'), ('sao cristovao', 'São Cristóvão'), ('apoio', 'Apoio'), ('intercessao', 'Intecessão'), ('sao miguel', 'São Miguel'), ('musicos', 'Músicos'), ('camarim', 'Camarim')], max_length=23, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('profissao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.profession', verbose_name='Profissão')),
            ],
            options={
                'verbose_name': 'Vocacionado',
                'verbose_name_plural': 'Vocacionados',
            },
        ),
    ]
