# Generated by Django 4.1.10 on 2023-08-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocacionados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocacionados',
            name='data_entrada',
            field=models.DateField(blank=True, null=True, verbose_name='Data de entrada'),
        ),
    ]
