# Generated by Django 4.1.10 on 2023-08-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocacionados', '0002_vocacionados_data_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocacionados',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='vocacionados',
            name='formacao_academica',
            field=models.CharField(blank=True, choices=[('Ensino Médio', 'Ensino Médio'), ('Graduação', 'Graduação'), ('Pós-graduação', 'Pós-graduação'), ('Mestrado ou Doutorado', 'Mestrado ou Doutorado'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Especialização', 'Especialização'), ('Técnico', 'Técnico'), ('Tecnológico', 'Tecnológico')], max_length=22, null=True, verbose_name='Formação Acadêmica'),
        ),
        migrations.AlterField(
            model_name='vocacionados',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
