# Generated by Django 4.2.4 on 2023-08-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocacionados', '0003_alter_vocacionados_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocacionados',
            name='formacao_academica',
            field=models.CharField(blank=True, choices=[('aprendizado_online', 'Aprendizado Online'), ('bacharelado', 'Bacharelado'), ('doutorado', 'Doutorado'), ('educacao_continuada', 'Educação Continuada'), ('ensino fundamental', 'Ensino Fundamental'), ('ensino medio', 'Ensino Médio'), ('especializacao', 'Especialização'), ('graduacao', 'Graduação'), ('licenciatura', 'Licenciatura'), ('mestrado', 'Mestrado'), ('mba', 'MBA (Master of Business Administration)'), ('phd', 'Ph.D.'), ('pos-graduacao', 'Pós-graduação'), ('tecnico', 'Técnico'), ('tecnologo', 'Tecnologo')], max_length=22, null=True, verbose_name='Formação Acadêmica'),
        ),
        migrations.AlterField(
            model_name='vocacionados',
            name='pastorais',
            field=models.CharField(choices=[('cozinha', 'Cozinha'), ('central de comunicacao', 'Central de comunicação'), ('lanchonete', 'Lanchonete(Quarta/Quinta)'), ('merce', 'Merce'), ('liturgia', 'Liturgia'), ('adoracao', 'Adoração'), ('limpeza', 'Limpeza'), ('loja', 'Loja'), ('bazar', 'Bazar'), ('sao cristovao', 'São Cristóvão'), ('apoio', 'Apoio'), ('intercessao', 'Intercessão'), ('sao miguel', 'São Miguel'), ('musicos', 'Músicos'), ('camarim', 'Camarim')], default=1, max_length=23),
            preserve_default=False,
        ),
    ]
