# Generated by Django 4.2.4 on 2023-08-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocacionados', '0003_alter_vocacionados_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocacionados',
            name='formacao_academica',
            field=models.CharField(blank=True, choices=[('ensino fundamental', 'Ensino Fundamental'), ('Ensino Médio', 'Ensino Médio'), ('Graduação', 'Graduação'), ('Pós-graduação', 'Pós-graduação'), ('Mestrado ou Doutorado', 'Mestrado ou Doutorado'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Especialização', 'Especialização'), ('Técnico', 'Técnico'), ('Tecnológico', 'Tecnológico')], max_length=22, null=True, verbose_name='Formação Acadêmica'),
        ),
    ]
