# Generated by Django 4.2.4 on 2023-08-20 09:01

import apps.pastorais.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocacionados', '0004_alter_vocacionados_formacao_academica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocacionados',
            name='pastorais',
            field=models.CharField(max_length=23, verbose_name=apps.pastorais.models.Pastorais),
        ),
    ]
