# Generated by Django 4.2.4 on 2023-08-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocacionados', '0004_alter_vocacionados_formacao_academica'),
        ('vocacionados', '0006_remove_vocacionados_pastorais_vocacionados_pastorais'),
    ]

    operations = [
    ]
