# Generated by Django 4.2.4 on 2023-08-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocacionados', '0007_merge_20230820_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocacionados',
            name='formacao_academica',
            field=models.CharField(blank=True, choices=[('aprendizado_online', 'Aprendizado Online'), ('bacharelado', 'Bacharelado'), ('doutorado', 'Doutorado'), ('educacao_continuada', 'Educação Continuada'), ('ensino fundamental', 'Ensino Fundamental'), ('ensino medio', 'Ensino Médio'), ('especializacao', 'Especialização'), ('graduacao', 'Graduação'), ('licenciatura', 'Licenciatura'), ('mestrado', 'Mestrado'), ('mba', 'MBA (Master of Business Administration)'), ('phd', 'Ph.D.'), ('pos-graduacao', 'Pós-graduação'), ('tecnico', 'Técnico'), ('tecnologo', 'Tecnologo')], max_length=22, null=True, verbose_name='Formação Acadêmica'),
        ),
    ]
