# Generated by Django 4.1.10 on 2023-08-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastorais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastorais',
            options={'verbose_name_plural': 'Pastorais'},
        ),
        migrations.RemoveField(
            model_name='pastorais',
            name='member',
        ),
    ]
