# Generated by Django 4.1.10 on 2023-08-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastorais', '0002_alter_pastorais_options_remove_pastorais_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastorais',
            old_name='pastoral',
            new_name='nome',
        ),
    ]
