# Generated by Django 4.2.4 on 2023-08-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastorais', '0004_alter_pastorais_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastorais',
            name='nome',
            field=models.CharField(choices=[('cozinha', 'Cozinha'), ('central de comunicacao', 'Central de comunicação'), ('lanchonete', 'Lanchonete(Quarta/Quinta)'), ('messe', 'Messe'), ('liturgia', 'Liturgia'), ('adoracao', 'Adoração'), ('limpeza', 'Limpeza'), ('loja', 'Loja'), ('bazar', 'Bazar'), ('sao cristovao', 'São Cristóvão'), ('apoio', 'Apoio'), ('intercessao', 'Intercessão'), ('sao miguel', 'São Miguel'), ('musicos', 'Músicos'), ('camarim', 'Camarim'), ('revista', 'Revista'), ('pastoral de rua', 'Pastoral de Rua'), ('conselho do 3º elo', 'Conselho do 3º Elo'), ('conselho geral', 'Conselho Geral'), ('formadora geral', 'Formadora Geral')], max_length=23),
        ),
    ]
