# Generated by Django 4.2.4 on 2023-08-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, choices=[('1_elo', '1º elo'), ('2_elo', '2º elo'), ('3_elo', '3º elo')], max_length=23, null=True)),
            ],
        ),
    ]
