# Generated by Django 4.2.4 on 2023-08-14 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elos',
            options={'verbose_name': 'Elo', 'verbose_name_plural': 'Elos'},
        ),
    ]
