# Generated by Django 4.2.4 on 2023-08-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elos', '0002_alter_elos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elos',
            name='nome',
            field=models.CharField(choices=[('1_elo', '1º elo'), ('2_elo', '2º elo'), ('3_elo', '3º elo')], max_length=23),
        ),
    ]
