# Generated by Django 4.2.4 on 2023-08-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elos', '0004_elos_membro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elos',
            name='membro',
        ),
    ]
