# Generated by Django 4.2.4 on 2023-08-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastorais', '0006_alter_pastorais_nome'),
        ('historico', '0002_historico_lista_pastorais_adicionadas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico',
            name='lista_pastorais_adicionadas',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='lista_pastorais_removidas',
        ),
        migrations.AddField(
            model_name='historico',
            name='pastorais_adicionadas',
            field=models.ManyToManyField(blank=True, related_name='historicos_adicionados', to='pastorais.pastorais'),
        ),
        migrations.AddField(
            model_name='historico',
            name='pastorais_removidas',
            field=models.ManyToManyField(blank=True, related_name='historicos_removidos', to='pastorais.pastorais'),
        ),
    ]
