# Generated by Django 4.2.4 on 2023-08-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastorais', '0006_alter_pastorais_nome'),
        ('historico', '0003_remove_historico_lista_pastorais_adicionadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='pastorais_atuais',
            field=models.ManyToManyField(blank=True, related_name='historicos_atuais', to='pastorais.pastorais'),
        ),
    ]
