# Generated by Django 4.2.4 on 2023-08-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntarios',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='voluntarios',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='voluntarios',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='voluntarios',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='voluntarios',
            name='estado',
        ),
        migrations.AddField(
            model_name='voluntarios',
            name='data_entrada',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='voluntarios',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
