# Generated by Django 4.2.4 on 2023-08-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastorais', '0003_rename_pastoral_pastorais_nome'),
        ('voluntarios', '0002_remove_voluntarios_bairro_remove_voluntarios_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntarios',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default=1, max_length=1, verbose_name='Sexo'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='voluntarios',
            name='pastorais',
        ),
        migrations.AddField(
            model_name='voluntarios',
            name='pastorais',
            field=models.ManyToManyField(blank=True, related_name='voluntarios_pastorais', to='pastorais.pastorais', verbose_name='Pastorais'),
        ),
    ]
