# Generated by Django 4.2.4 on 2023-08-25 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
